"""Authoritative grader.  Run as ``python3 -I -S /tests/check_submission.py``.

Exit status:
  0  every graded value is within tolerance; the verdict line is printed
  1  the submission violates a stated requirement (contract or accuracy)
  2  verifier infrastructure error (truth derivation, digest, unexpected exception)

Files opened: /app/output/model.json (the declared artifact, through
answer_format, which refuses anything but a bounded regular file) and the
modules in /tests.  Ground truth is regenerated by a separate isolated
interpreter; no truth file exists on disk, so no path the agent controls can
point the grader at it.
"""

import json
import os
import subprocess
import sys

# -I implies -P: put this file's directory (/tests, the read-only verify-time
# overlay) on sys.path so the sibling modules can be imported.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import answer_format  # noqa: E402
import frame_model  # noqa: E402

VERDICT = "VSF-GRADER: PASS all 164 natural frequencies within tolerance"
FREQ_REL_TOL = 0.03
N_CONFIGS = 41
DERIVE_TIMEOUT_S = 150


class InfraError(Exception):
    pass


def load_truth():
    here = os.path.dirname(os.path.abspath(__file__))
    proc = subprocess.run([sys.executable, "-I", "-S", os.path.join(here, "derive_truth.py")],
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                          timeout=DERIVE_TIMEOUT_S, check=False)
    if proc.returncode != 0:
        raise InfraError("derive_truth exited %d: %s" % (proc.returncode, proc.stderr.decode(errors="replace")))
    truth = json.loads(proc.stdout.decode("ascii"))
    if len(truth["configs"]) != N_CONFIGS:
        raise InfraError("unexpected number of configurations")
    return truth


def grade(k, truth):
    """Return a list of failure messages (empty when everything passes)."""
    m = truth["as_tested_mass_kg"]
    failures = []
    for row in truth["configs"]:
        cid = row["id"]
        try:
            f = frame_model.configuration_frequencies(k, m, row["added_mass_kg"], row["stiffness_factor"])
        except (ArithmeticError, ValueError) as exc:
            failures.append("%s: submitted model cannot be evaluated (%s)" % (cid, exc))
            continue
        for i in range(4):
            err = abs(f[i] / row["f_hz"][i] - 1.0)
            if not err <= FREQ_REL_TOL:
                failures.append("%s: natural frequency %d is %.6g Hz, true %.6g Hz (rel. error %.3g > %.3g)"
                                % (cid, i + 1, f[i], row["f_hz"][i], err, FREQ_REL_TOL))
    return failures


def main():
    try:
        k = answer_format.read_model()
    except answer_format.ContractError as exc:
        print("FAIL contract: %s" % exc)
        return 1
    truth = load_truth()
    failures = grade(k, truth)
    if failures:
        print("FAIL accuracy: %d of 164 natural frequencies out of tolerance" % len(failures))
        for msg in failures[:25]:
            print("  " + msg)
        return 1
    print(VERDICT)
    return 0


if __name__ == "__main__":
    try:
        code = main()
    except BaseException as exc:  # never let an infrastructure fault read as a model failure
        sys.stderr.write("VERIFIER INFRASTRUCTURE ERROR: %r\n" % (exc,))
        code = 2
    sys.exit(code)
