"""Itemised report for /app/output/model.json.

The reward is decided by check_submission.py; this module renders one test per
requirement of the instruction.  Contract tests come first; accuracy tests
skip (and the reward stays 0) when the contract is not met.
"""

import json
import os
import stat
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import answer_format  # noqa: E402
import frame_model  # noqa: E402

FREQ_REL_TOL = 0.03


@pytest.fixture(scope="module")
def submission():
    """Parsed stiffness list from the artifact, or the ContractError explaining why not."""
    try:
        return answer_format.read_model()
    except answer_format.ContractError as exc:
        return exc


@pytest.fixture(scope="module")
def truth():
    """Ground truth regenerated by derive_truth.py in an isolated interpreter (-I -S)."""
    here = os.path.dirname(os.path.abspath(__file__))
    proc = subprocess.run([sys.executable, "-I", "-S", os.path.join(here, "derive_truth.py")],
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=150, check=True)
    return json.loads(proc.stdout.decode("ascii"))


def _require_contract(submission):
    if isinstance(submission, Exception):
        pytest.skip("output contract not met: %s" % submission)
    return submission


def _out_of_tolerance(k, truth, rows):
    bad = []
    for row in rows:
        f = frame_model.configuration_frequencies(k, truth["as_tested_mass_kg"], row["added_mass_kg"],
                                                  row["stiffness_factor"])
        for i in range(4):
            if not abs(f[i] / row["f_hz"][i] - 1.0) <= FREQ_REL_TOL:
                bad.append("%s f%d %.6g Hz vs true %.6g Hz" % (row["id"], i + 1, f[i], row["f_hz"][i]))
    return bad


def test_artifact_is_bounded_regular_file():
    """/app/output/model.json exists and is a regular file (not a symlink, FIFO or device) of at most 64 KiB."""
    st = os.lstat(answer_format.ARTIFACT)
    assert stat.S_ISREG(st.st_mode), "model.json must be a regular file"
    assert st.st_size <= answer_format.MAX_BYTES, "model.json must be at most 65536 bytes"


def test_model_json_matches_contract(submission):
    """The file is a JSON object whose only key is k: a list of four numbers, each in [1, 1e9] N/m."""
    assert not isinstance(submission, Exception), str(submission)
    assert len(submission) == 4


def test_tested_frame_natural_frequencies(submission, truth):
    """With the as-tested masses, the submitted stiffnesses give all four natural frequencies within 3 % of the true ones."""
    k = _require_contract(submission)
    bad = _out_of_tolerance(k, truth, truth["configs"][:1])
    assert not bad, "tested frame: %s" % bad


def test_heldout_mass_only_variants(submission, truth):
    """Every held-out variant that only adds floor masses has all four natural frequencies within 3 %."""
    k = _require_contract(submission)
    rows = [r for r in truth["configs"][1:] if r["stiffness_factor"] == [1.0, 1.0, 1.0, 1.0]]
    bad = _out_of_tolerance(k, truth, rows)
    assert not bad, "%d frequencies out of tolerance, e.g. %s" % (len(bad), bad[:5])


def test_heldout_stiffness_variants(submission, truth):
    """Every held-out variant that also scales one storey stiffness has all four natural frequencies within 3 %."""
    k = _require_contract(submission)
    rows = [r for r in truth["configs"][1:] if r["stiffness_factor"] != [1.0, 1.0, 1.0, 1.0]]
    bad = _out_of_tolerance(k, truth, rows)
    assert not bad, "%d frequencies out of tolerance, e.g. %s" % (len(bad), bad[:5])
